### PR TITLE
Abort playbook early without extra var, remove custom confirmation implementation

### PR DESCRIPTION
**Pull request by ollytom**
Abort playbook early without extra var

We can use the failed_when property of a task to abort the playbook early. This lets us isolate the logic to a single task.

Remove custom confirmation implementation

We can let the caller of the role prompt for confirmation (if desired). This can be done with a playbook prompt https://docs.ansible.com/ansible/latest/user_guide/playbooks_prompts.html Usually ansible roles do not roll their own own confirmation implementation.

### CODE REVIEW

**Review by vk2amv — COMMENTED** [review]
Cannot mege this as duplicate TC Interfaces check is required.

As per Shorewall documentation you cannot have duplicate TC Interfaces entries in both Shorewall and Shorewall6 vars so we need to sanity check the vars before proceeding.

**Review by vk2amv — COMMENTED** [review]
This commit is basically just removing the Shorewall_run check while leaving the Shorewall6_run in place but changing the name of the Shorewall6_run check to Shorewall6_enabled

The playbook prompts is not what we want for this purpose, and would break too many existing host vars that currently exist.

**Comment by ollytom** [comment]
Hey hold your horses, let's just do one more quick round of review!

> Cannot merge this as duplicate TC Interfaces check is required.

There is still a check. Granted it's harder to see as I submitted these 2 patches in a single PR. My mistake! Let me resubmit 9d07e5a1cf90c in isolation and let me know what you think :)

> The playbook prompts is not what we want for this purpose, and would
> break too many existing host vars that currently exist.

Ah that makes sense. Thanks for explaining! It sounds like this role depends a lot on the particular sol1 environment in which it runs. Maybe this role isn't the best candidate to be made open source?
What do you think about maintaining this role in the `roles/` directory of an ansible config repository to ease dependency management?

**Comment by davekempe** [comment]
> Ah that makes sense. Thanks for explaining! It sounds like this role depends a lot on the particular sol1 environment in which it runs. Maybe this role isn't the best candidate to be made open source? What do you think about maintaining this role in the `roles/` directory of an ansible config repository to ease dependency management?

I would like to keep this role open. I'm sure we can work something out. 

Keep in mind that safety with this role is very important. Its very easy to cut your hands off with shorewall, unlike many other roles. It makes sense it has some Right Side failure built in: https://en.wikipedia.org/wiki/Wrong-side_failure

If anything I would suggest we try and just make it smarter still.

**Comment by ollytom** [comment]
> Keep in mind that safety with this role is very important. Its very easy to cut your hands off with shorewall,

Yeah that makes sense. Anyway I'll submit that other patch now, closing this one off ...

**Pull request closed without merging**
